### ISSUE TITLE
Modrinth marked as client side “unsupported”

### ISSUE THREAD

**Issue by Daniel99j2** [henkelmax/status#18]
**Bug description**
On modrinth, the client side mod is marked as unsupported

**Steps to reproduce the issue**
1. Go to the modrinth page
2. Client side is marked as unsupported

**Expected behavior**
Client side should be marked as “optional”, as it is required to set a status

**Screenshots (Optional)**
<img width="375" alt="image" src="https://github.com/henkelmax/status/assets/121533735/07d95714-8631-4adb-97e3-143dad4ee5cc">

**Comment by henkelmax** [comment]
Sorry for the inconvenience, there was a missing label, which caused the bot to auto close issues.

**Comment by henkelmax** [comment]
There currently seems to be a bug in Modrinth. It keeps resetting it to unsupported when trying to set the client side from unsupported to optional.
I'll keep you updated once it works.

EDIT:
https://github.com/modrinth/code/issues/1416

**Comment by henkelmax** [comment]
I've changed it to required on the client and server side for now.
