### ISSUE TITLE
Clickable Message Doesn't Open GUI

### ISSUE THREAD

**Issue by AllOutJay** [henkelmax/status#23]
### Bug description

When I click on the reminder message that I get when I join a server, the GUI doesn't open up. I've tried disabling all my mods aside from the Status and Fabric api mods, but that doesn't appear to make a difference. The Status mod is also installed on the Fabric server.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.0.6

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

1. Have Fabric, Fabric api, Status installed both on the client and server
2. Log into a server
3. View reminder message in the chat
4. Click reminder message in the chat
5. See that no gui opens :(

### Expected behavior

gui should open when reminder message is clicked.

### Log files

N/A

**Comment by henkelmax** [comment]
The GUI is not clickable.
https://github.com/henkelmax/status/blob/6492a098d6e2dec7e43286bd650846a37aa355ec/src/main/java/de/maxhenkel/status/playerstate/ClientPlayerStateManager.java#L96-L104

**Comment by AllOutJay** [comment]
@henkelmax you may want to update the Modrinth page then since the following is misleading and conveys the idea that one can click the reminder message to get the gui to popup: "When joining a server the first time in your playing session, you will get a **_clickable message_** that will remind you to set your status. The status is not persisted between playing sessions by default."

**Comment by henkelmax** [comment]
Yeah, I need to update that, sorry. It was clickable before, but due to changes in Minecraft/Fabric its not possible anymore, since the chat GUI somehow overrides the GUI thats opened with the click.
