### ISSUE TITLE
Help With Installation

### ISSUE THREAD

**Issue by ThrillerGriller** [henkelmax/status#3]
Hello! I've been having some difficulty with downloading the status mod. Usually, mods come as a jar file, which you can easily drag into your mods folder or server. This mod however doesn't seem to come as a jar file, rather a file filled with many things that don't seem to contribute to the mod itself.

It'd be greatly appreciated if you could tell me to steps to get this running on my client. This is not only for me, but also for others who I have noticed are experiencing the same issues. I've checked through youtube and tutorials and found nothing as well.

**Versions**
- Minecraft Fabric 1.19.2
- fabric-loader-0.14.9-1.19.2
- fabric-api-0.60.0+1.19.2
- status-1.19.2

**Other mods**
voicechat-fabric-1.19.2-2.3.8
modmenu-4.0.6

As you can see from the image below, I put the whole folder into the mod folder and it doesn't show up on the mod menu. So I'm guessing that's not the way of doing it.
![image](https://user-images.githubusercontent.com/112766044/188274417-e5657e3d-9eca-480a-ac43-f9756eade547.png)

**Comment by henkelmax** [comment]
You need to download the mod from the releases section.
