### ISSUE TITLE
Support for Spigot servers?

### ISSUE THREAD

**Issue by isnotbrae** [henkelmax/status#4]
Hey there. Just trying to figure out if this mod is compatible with Spigot servers running Fabric.

I’m running the 1.19 version of the mod on a server of the same version however whenever my friend and I join the server, we are unable to see each other’s statuses. The mod is installed on both of our clients as well as on the server.

Thanks!

**Comment by henkelmax** [comment]
Spigot and hybrid servers are not supported.
