### ISSUE TITLE
Missing hotkey settings

### ISSUE THREAD

**Issue by meza** [henkelmax/status#5]
Some of the players in our community have their U keys mapped to other features they don't want to give up. It would be amazing to be able to set the keybind to bring up the gui. Or even a /status command.
Currently this is the only missing feature that's preventing our server from fully adopting the status mod. I fully know that it shouldn't be a blocker but alas...
Adding a setting would make the mod ever so slightly more accessible.

**Comment by henkelmax** [comment]
Just change the key in the keybind settings??

**Comment by meza** [comment]
Yeah, both my users and me were completely blind. Didn't expect it to be in the misc area.  😅 My bad
