### ISSUE TITLE
I made some nicer UI

### ISSUE THREAD

**Issue by theDerxu** [henkelmax/status#6]
This is the only way I know of contacting the mod so sorry if this is the wrong place but, I made some nicer looking UI elements and were wandering if you would like them?
I don't need credit or anything I just made them for personal use.
![open](https://user-images.githubusercontent.com/88974734/209242655-817b2a59-96f5-4a32-b2e8-5c9b5bc01178.png)
![recording](https://user-images.githubusercontent.com/88974734/209242657-e3a99a6d-b826-4527-99af-e630f689318a.png)
![streaming](https://user-images.githubusercontent.com/88974734/209242658-39b55744-8d08-4d63-b1d3-a97c19319cf8.png)
![dnd](https://user-images.githubusercontent.com/88974734/209242659-6339c561-9f9e-4c38-9b5e-7742c00af6b6.png)
![neutral](https://user-images.githubusercontent.com/88974734/209242661-8670b11e-363c-4955-893c-5a6c22b20b7e.png)
![no_availability](https://user-images.githubusercontent.com/88974734/209242662-b189cfd6-bc63-4670-b990-695ae70b2e95.png)

**Comment by theDerxu** [comment]
I don't know how to / if I can add the enhancement label and remove the bug one :p

**Comment by henkelmax** [comment]
You can create a resource pack with these icons, but I won't add these. I was requested by the hermits to use these specific icons. This is also the only purpose the mod serves.
