### ISSUE TITLE
Feather client

### ISSUE THREAD

**Issue by Divyde** [henkelmax/status#7]
**Bug description**
Feather client support for the mod

**Steps to reproduce the issue**
1. Go to 'Feather 1.19.2'
2. Import mod
3. try launch client
4. Feather error message (not the fabric pop up)

**Expected behavior**
game would launch normally I hope
**Log files**
[latest.log](https://github.com/henkelmax/status/files/10441057/latest.log)

**Versions**
- Minecraft version     1.19.2
- Fabric Loader version     most recent
- Fabric API version        also most recent    (assuming feather has most recent)
- Mod version    1.19.2 1.0.0

**Other mods**
Feather doesnt run with only status mod anyways but 
Starlight
entity culling
effective
essential
lithium
mod menu
no chat reports
replay mod
simple voice chat
sodium

**Comment by Divyde** [comment]
1.19 doesnt work either

**Comment by henkelmax** [comment]
Custom clients are not supported and there won't be support for it in the future, sorry.
