### ISSUE TITLE
Spigot Support

### ISSUE THREAD

**Issue by c1oudychan** [henkelmax/status#8]
**Bug description**
Plugin to connect Server and Client

**Steps to reproduce the issue**
1. Go to ['this git'](https://github.com/henkelmax/status)
2. See there is no Spigot plugin
3. Cry.

**Expected behavior**
Spigot plugin.

**Log files**
No logs.

**Versions**
- Minecraft version - 1.19.3
- ~~Fabric Loader version~~
- ~~Fabric API version~~
- ~~Mod~~ Plugin version

**Other mods**
No other mods

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/96329203/226271953-663a774f-c363-4e70-a0c9-e5d469c27da7.png)

**Comment by henkelmax** [comment]
Sorry, there won't be any ports to other platforms. This is just made for the hermitcraft server. And thats running fabric.
